
class Constants:
    START = '~'
    END = '~'
    ACKNOWLEDGE_COMMAND = "ACK"
    NOT_ACKNOWLEDGE_COMMAND = "NAK"
    HANDSHAKE_COMMAND = "HAN"
    WRITE_ALL_COMMAND = "WRT"
    WRITE_ALL_RESPOND = "ALL"
    SET_CURRENT_COMMAND = "CUR"
    SET_VOLTAGE_COMMAND = "VOL"
    SET_OUTPUT_ON_COMMAND = "OUT"

